### ISSUE TITLE
How to deploy this blog system

### ISSUE THREAD

**Issue by ArtUsr** [pioug/blog#2]
thx your nice work

**Comment by pioug** [comment]
You must have access to GitHub Actions (I think it is still in beta?). Then you can start by forking/copying the repository. You will need to set the following environment variables
![image](https://user-images.githubusercontent.com/3654180/62699846-086cbe00-ba13-11e9-81a8-83bd0fcb79c4.png)
So all the scripts can have access to the repository issues and can publish an update.

Thanks for you interest. I will work on a readme!
