### ISSUE TITLE
it seems the GraphQL API is not work

### ISSUE THREAD

**Issue by ArtUsr** [pioug/blog#3]
rewrite the gulpfile.js
```
headers: {
      Authorization: `Bearer ${GH_API_TOKEN}`,
      "User-Agent": "ArtUsr"
    },
    asJSON: true
  });
```
And
```
 query ($number_of_issues: Int!) {
      repository(owner:"ArtUsr", name:"blog")
```        
Before this modify , i have already enable issues and Store GitHub access token as Secrets.
My repository  https://github.com/ArtUsr/1st

**Comment by ArtUsr** [comment]
```
> blog@0.0.0 build /github/workspace
> npx eleventy

Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk template ./feed/feed.njk (TemplateContentRenderError)
> (unknown path)
  Error: Collection is empty in rssLastUpdatedDate filter. (Template render error):
    Template render error: (unknown path)
      Error: Collection is empty in rssLastUpdatedDate filter.
        at Object._prettifyError (/github/workspace/node_modules/nunjucks/src/lib.js:36:11)
        at /github/workspace/node_modules/nunjucks/src/environment.js:567:19
         at Template.root [as rootRenderFunc] (eval at _compile (/github/workspace/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:79:3)
        at Template.render (/github/workspace/node_modules/nunjucks/src/environment.js:556:10)
at /github/workspace/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:136:14
        at new Promise (<anonymous>)
        at /github/workspace/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:135:14
        at Template.render (/github/workspace/node_modules/@11ty/eleventy/src/TemplateContent.js:160:28)
         at process._tickCallback (internal/process/next_tick.js:68:7)
Benchmark (Configuration): "htmlDateString" Nunjucks Filter took 206ms (39.1%)
Copied 2 items and Processed 0 files in 0.39 seconds
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blog@0.0.0 build: `npx eleventy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blog@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2019-08-31T13_27_26_754Z-debug.log
```

**Comment by ArtUsr** [comment]
i have solved . it's Personal access tokens Configuration error

**Comment by ArtUsr** [comment]
The error seems to have been caused by Personal access tokens. You can tell which permissions you want to check.

**Comment by ArtUsr** [comment]
> blog@0.0.0 build /github/workspace
> npx eleventy

Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk template ./feed/feed.njk (TemplateContentRenderError)
> (unknown path)
  Error: Collection is empty in rssLastUpdatedDate filter. (Template render error):
    Template render error: (unknown path)
       Error: Collection is empty in rssLastUpdatedDate filter.
        at Object._prettifyError (/github/workspace/node_modules/nunjucks/src/lib.js:36:11)
        at /github/workspace/node_modules/nunjucks/src/environment.js:567:19
        at Template.root [as rootRenderFunc] (eval at _compile (/github/workspace/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:79:3)
        at Template.render (/github/workspace/node_modules/nunjucks/src/environment.js:556:10)
 at /github/workspace/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:136:14
        at new Promise (<anonymous>)
        at /github/workspace/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:135:14
        at Template.render (/github/workspace/node_modules/@11ty/eleventy/src/TemplateContent.js:160:28)
        at process._tickCallback (internal/process/next_tick.js:68:7)
Benchmark (Configuration): "htmlDateString" Nunjucks Filter took 201ms (38.4%)
Copied 2 items and Processed 0 files in 0.39 seconds
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blog@0.0.0 build: `npx eleventy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blog@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2019-08-31T14_07_46_944Z-debug.log
 Deploying to GitHub...
[master aed2c57] Deploying to gh-pages - 14:07:46
 3 files changed, 208 insertions(+)
  create mode 100644 _site/css/index.css
 create mode 100644 _site/css/prism-base16-monokai.dark.css
 create mode 100644 _site/img/.gitkeep
1/18 (0)
2/18 (1)
3/18 (2)
4/18 (3)
5/18 (4)
6/18 (5)
7/18 (6)
8/18 (7)
9/18 (8)
10/18 (9)
11/18 (10)
12/18 (11)
13/18 (12)
14/18 (13)
15/18 (14)
16/18 (15)
17/18 (16)
18/18 (17)
error: src refspec ***@github.com/ArtUsr/blog.git does not match any.
error: failed to push some refs to 'https://'
##[error]Docker run failed with exit code 1

**Comment by pioug** [comment]
The label `posts` is currently required to include the issues as blog posts. 

```js
// gulpfile.js
issues
  .filter(({ node: { labels: { edges: labels } } }) =>
    labels.some(({ name }) => "posts")
  )
```

Can you try labelling your issues with `posts`? I am sorry my repo is still in early stage. I haven't thought about reusability yet.
